//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentuDY.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderTransaction
    {
        public int TransactionId { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransactionDate { get; set; }
    }
}
